project:
  output-dir: ../outpout/Pioneer
book:
  chapters:
  - index.qmd
  - part: New cards
    chapters:
    - 1_new_card.qmd
  - part: Metagame
    chapters:
    - 2_presence_archetype.qmd
    - 4_matrix_WR.qmd
  - part: Deck winrate
    chapters:
    - 3_Card_win_rate_table.qmd
    - 5_Deck_analysis.qmd
  - part: Best performing deck
    chapters:
    - 6_best_deck.qmd
    - 7_last_weeks_winners.qmd
